name: Build and upload to S3
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: go build . -o $HOME/fibo

      - name: Test
        run: go test -v .

      - name: Benchmark
        run: go test -v . -bench=.

      - name: List files 
        run:  ls -alrt $HOME

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: $HOME
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
