name: My Simple Pipeline to S3
on: [push, pull_request]
jobs:
  build:
    name: Test and Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@master

      - name: Build
        run: go build .

      - name: Test
        run: go test -v .

      - name: Benchmark
        run: go test -v . -bench=.  2>&1 | tee $GITHUB_WORKSPACE/latest-benchmarks.txt

      - name: List Files
        run: ls -alrt $GITHUB_WORKSPACE

      - name: Upload bencmark artifacts
        uses: actions/upload-artifact@master
        with:
          name: benchmark-report.txt
          path: latest-benchmarks.txt


  deploy:
    name: Build and Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
          go-version: 1.13

    - name: Check out master branch
      uses: actions/checkout@master

    - name: Build
      run: go build .

    - name: Upload binary to S3 bucket
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        FILE: ./gh-actions-golang
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
